### ISSUE TITLE
Roadmap for v0.2.1, v02.2. etc. (cont'd)

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-fileformat#30]
Copied from https://github.com/UB-Mannheim/ocr-fileformat/issues/29#issuecomment-246387868 by @kba:
- [x] Merge https://github.com/UB-Mannheim/ocr-fileformat/tree/to-text
- [x] Merge https://github.com/UB-Mannheim/ocr-fileformat/tree/gcv (kinda blocked by   dinosauria123/gcv2hocr#3)
- [ ] Revise and merge https://github.com/UB-Mannheim/ocr-fileformat/tree/better-testing (since that would be helpful indeed).

**Comment by zuphilip** [comment]
"to-text" was merged in https://github.com/UB-Mannheim/ocr-fileformat/commit/db1da009785a870e01a73889e89742db3b299db5 which is already part of `v0.2.0`

**Comment by zuphilip** [comment]
The remaining open task here can be continued in #41.
